### PR TITLE
kernel: Re-work compat symbols detection

### LINKED ISSUE #95: Unable to compile kernel module Ubuntu/Rocky
On newly installed Ubuntu LTS server
```
root@sp01:/tmp# date
Thu 10 Mar 2022 11:55:42 AM CET

root@sp01:/tmp# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

root@sp01:/tmp# uname -a
Linux sp01 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

root@sp01:/tmp# git clone https://github.com/markh794/mhvtl.git
Cloning into 'mhvtl'...
remote: Enumerating objects: 8006, done.
remote: Counting objects: 100% (590/590), done.
remote: Compressing objects: 100% (387/387), done.
remote: Total 8006 (delta 381), reused 348 (delta 200), pack-reused 7416
Receiving objects: 100% (8006/8006), 3.18 MiB | 1.61 MiB/s, done.
Resolving deltas: 100% (5761/5761), done.

root@sp01:/tmp# cd mhvtl/kernel/

root@sp01:/tmp/mhvtl/kernel# make
make -C /lib/modules/5.4.0-100-generic/build M=/tmp/mhvtl/kernel modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.0-100-generic'
  CC [M]  /tmp/mhvtl/kernel/mhvtl.o
In file included from /tmp/mhvtl/kernel/mhvtl.c:95:
/tmp/mhvtl/kernel/backport.h:63:12: error: static declaration of ‘sysfs_emit’ follows non-static declaration
   63 | static int sysfs_emit(char *buf, const char *fmt, ...)
      |            ^~~~~~~~~~
In file included from ./include/linux/kobject.h:20,
                 from ./include/linux/module.h:17,
                 from /tmp/mhvtl/kernel/mhvtl.c:45:
./include/linux/sysfs.h:325:5: note: previous declaration of ‘sysfs_emit’ was here
  325 | int sysfs_emit(char *buf, const char *fmt, ...);
      |     ^~~~~~~~~~
make[2]: *** [scripts/Makefile.build:270: /tmp/mhvtl/kernel/mhvtl.o] Error 1
make[1]: *** [Makefile:1762: /tmp/mhvtl/kernel] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-100-generic'
make: *** [Makefile:26: default] Error 2

root@sp01:/tmp/mhvtl/kernel#
```

Same situation on Rocky Linux 8
```
[root@sp02 kernel]# make
make -C /lib/modules/4.18.0-348.el8.0.2.x86_64/build M=/tmp/mhvtl/kernel modules
make[1]: Entering directory '/usr/src/kernels/4.18.0-348.12.2.el8_5.x86_64'
  CC [M]  /tmp/mhvtl/kernel/mhvtl.o
In file included from /tmp/mhvtl/kernel/mhvtl.c:95:
/tmp/mhvtl/kernel/backport.h:63:12: error: static declaration of ‘sysfs_emit’ follows non-static declaration
 static int sysfs_emit(char *buf, const char *fmt, ...)
            ^~~~~~~~~~
In file included from ./include/linux/kobject.h:20,
                 from ./include/linux/module.h:17,
                 from /tmp/mhvtl/kernel/mhvtl.c:45:
./include/linux/sysfs.h:336:5: note: previous declaration of ‘sysfs_emit’ was here
 int sysfs_emit(char *buf, const char *fmt, ...);
     ^~~~~~~~~~
make[2]: *** [scripts/Makefile.build:322: /tmp/mhvtl/kernel/mhvtl.o] Error 1
make[1]: *** [Makefile:1571: _module_/tmp/mhvtl/kernel] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.18.0-348.12.2.el8_5.x86_64'
make: *** [Makefile:26: default] Error 2
[root@sp02 kernel]#
```

### PR DESCRIPTION
**Pull request by melak**
In the day and age of distros backporting various things from later
kernels to their shipped kernels, relying on kernel version numbers
for knowing whether a certain feature is available is not really
relyable.

Introduce a new auto-configure script that tries a little harder
to figure out whether some features (implemented in backports.h)
is necessary for a particular scenario. The method used is not
infallible and there probably is a more correct way, but it is
simple enough to solve the immediate problem.

Addresses and should fix #95

### CODE REVIEW

**Comment by melak** [comment]
This grepping business is not infallible - that would probably be actually trying to build dummy modules using the symbols under test, a'la autoconf, but I don't know autoconf, I don't want to know or implement autoconf :), and this is simple enough to bridge the current gap in a sufficiently clean manner.

Checked to work on Debian 9, Debian 11, Ubuntu 20.04, Ubuntu 22.04, AlmaLinux 8.5 and CentOS 7.

@gonzoleeman can you please check whether it also works in your neck of the woods?

**Comment by gonzoleeman** [comment]
I will check over the weekend. I’m off today. 

--
Lee-Man Duncan

**Comment by gonzoleeman** [comment]
The changes work for openSUSE Leap 15.2 and for Tumbleweed. Strangely, the order of the preprocessor undefs/defs is backwards in config.h between the two.

I would like to see guards added to the config.h, i.e. "#ifndef config_h ..." to guard against multiple inclusion.

If this method turns out to be an issue we will either have to move the kernel module into the kernel, or we will have to use autoconf.

**Comment by melak** [comment]
Include guard added.

That the order is (seemingly) random, or at least different across different systems is not particularly surprising.

**Comment by markh794** [comment]
Can you pass $(KDIR) to config.sh and use that instead of $(uname -r)

That way, the build isn't dependent on the running kernel.

Apart from that, it looks good to merge..

Many thanks for the work

**Comment by melak** [comment]
Fair point. This one can now build against any installed header set.

**Comment by markh794** [comment]
Committed- many thanks once again.

**Pull request merged**
